pipeline:
  name: Platform Pet Clinic
  identifier: Platform_Pet_Clinic
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.NavaliaHQ
        repoName: plat-petclinic-kotlin
        build: <+input>
  stages:
    - parallel:
        - stage:
            name: Unit Tests
            identifier: Tests_and_Lint
            description: ""
            type: CI
            spec:
              cloneCodebase: true
              caching:
                enabled: true
                override: true
                paths: []
              buildIntelligence:
                enabled: true
              platform:
                os: Linux
                arch: Arm64
              runtime:
                type: Docker
                spec:
                  harnessImageConnectorRef: Docker_Hub
              execution:
                steps:
                  - step:
                      type: Run
                      name: Unit Tests
                      identifier: Unit_Tests
                      spec:
                        connectorRef: Docker_Hub
                        image: openjdk:17-ea-slim-buster
                        shell: Bash
                        command: |-
                          chmod +x ./gradlew
                          ./gradlew cleanTest test
                        imagePullPolicy: IfNotPresent
            delegateSelectors:
              - gualter-machine
        - stage:
            name: Hadolint
            identifier: Hadolint
            description: ""
            type: CI
            spec:
              cloneCodebase: true
              caching:
                enabled: true
                override: true
              buildIntelligence:
                enabled: true
              platform:
                os: Linux
                arch: Arm64
              runtime:
                type: Docker
                spec:
                  harnessImageConnectorRef: Docker_Hub
              execution:
                steps:
                  - step:
                      type: Run
                      name: Run
                      identifier: Run
                      spec:
                        connectorRef: Docker_Hub
                        image: hadolint/hadolint
                        shell: Bash
                        command: hadolint ./Dockerfile
            delegateSelectors:
              - gualter-machine
        - stage:
            name: KLint
            identifier: KLint
            description: ""
            type: CI
            spec:
              cloneCodebase: true
              caching:
                enabled: true
                override: true
              buildIntelligence:
                enabled: true
              platform:
                os: Linux
                arch: Arm64
              runtime:
                type: Docker
                spec:
                  harnessImageConnectorRef: Docker_Hub
              execution:
                steps:
                  - step:
                      type: Run
                      name: Run
                      identifier: Run
                      spec:
                        shell: Bash
                        command: |-
                          chmod +x ./gradlew
                          ./gradlew ktlintCheck
            delegateSelectors:
              - gualter-machine
