pipeline:
  name: Platform Pet Clinic
  identifier: Platform_Pet_Clinic
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.NavaliaHQ
        repoName: plat-petclinic-kotlin
        build: <+input>
  stages:
    - stage:
        name: Tests and Lint
        identifier: Tests_and_Lint
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Docker
            spec:
              harnessImageConnectorRef: Docker_Hub
          execution:
            steps:
              - parallel:
                  - step:
                      type: Run
                      name: Unit Tests
                      identifier: Unit_Tests
                      spec:
                        connectorRef: Docker_Hub
                        image: openjdk:17-ea-slim-buster
                        shell: Bash
                        command: |-
                          chmod +x ./gradlew
                          ./gradlew cleanTest test
                        imagePullPolicy: IfNotPresent
                  - step:
                      type: Run
                      name: KLint
                      identifier: KLint
                      spec:
                        shell: Sh
                        command: |-
                          chmod +x ./gradlew
                          ./gradlew ktlintCheck
                  - step:
                      type: Run
                      name: Hadolint
                      identifier: Hadolint
                      spec:
                        shell: Bash
                        command: |-
                          wget -O hadolint https://github.com/hadolint/hadolint/releases/download/vX.Y.Z/hadolint-Linux-x86_64
                          chmod +x ./hadolint
                          ./hadolint --version
                          ./hadolint ./Dockerfile
        delegateSelectors:
          - gualter-machine
